In [ ]:
#In this code Multilingual dataset is used along with text preprocessing, tokenization, tfidf vectorization. 5-6 models are already added

In [1]:
# Array
import numpy as np

# Dataframe
import pandas as pd

#Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# warnings
import warnings
warnings.filterwarnings('ignore')

#Data Reading
data= pd.read_csv(r'D:\StressDetection\sentiment_analysis_term_train.csv')

# Copy
stress=data.copy()

# Data
stress.head()

text label
0  हमें इससे बेहतर ब्राइटनेस वाले टेबलेट देखने को...   neg
1                          बैटरी लाइफ बहुत बढिया है।   pos
2  हकीकत ये है कि मेटल के नाम पर फोन में सिर्फ चा...   neu
3  स्लोफो एक मनोरंजक एप्लिकेशन है इसमें कोई दो रा...   pos
4                             अच्छी बैटरी क्षमता है।   pos

In [2]:
# Info
stress.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2497 entries, 0 to 2496
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    2497 non-null   object
 1   label   2497 non-null   object
dtypes: object(2)
memory usage: 39.1+ KB


In [3]:
# Checking null values
stress.isnull().sum()

text     0
label    0
dtype: int64

In [4]:
# Statistical Information
stress.describe()

text label
count                                                2497  2497
unique                                               2497     3
top     हमें इससे बेहतर ब्राइटनेस वाले टेबलेट देखने को...   pos
freq                                                    1  1147

In [5]:
import pandas as pd
from transformers import MarianMTModel, MarianTokenizer
from wordcloud import WordCloud
import matplotlib.pyplot as plt

In [6]:
model_name = "Helsinki-NLP/opus-mt-mul-en"
tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)

In [7]:
# Translate text from any supported language to English
def translate(text, source_lang="auto"):
    try:
        inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, source_lang=source_lang)
        outputs = model.generate(**inputs)
        translated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
        return translated_text
    except Exception as e:
        print(f"Translation error: {e}")
        return None

In [8]:
# Replace the 'text' column with translated English text
data['text'] = data['text'].apply(lambda x: translate(x, source_lang="hi"))

data = data.dropna(subset=['text'])

Keyword arguments {'source_lang': 'hi'} not recognized.
Keyword arguments {'source_lang': 'hi'} not recognized.
Keyword arguments {'source_lang': 'hi'} not recognized.
Keyword arguments {'source_lang': 'hi'} not recognized.
Keyword arguments {'source_lang': 'hi'} not recognized.
Keyword arguments {'source_lang': 'hi'} not recognized.
Keyword arguments {'source_lang': 'hi'} not recognized.
Keyword arguments {'source_lang': 'hi'} not recognized.
Keyword arguments {'source_lang': 'hi'} not recognized.
Keyword arguments {'source_lang': 'hi'} not recognized.
Keyword arguments {'source_lang': 'hi'} not recognized.
Keyword arguments {'source_lang': 'hi'} not recognized.
Keyword arguments {'source_lang': 'hi'} not recognized.
Keyword arguments {'source_lang': 'hi'} not recognized.
Keyword arguments {'source_lang': 'hi'} not recognized.
Keyword arguments {'source_lang': 'hi'} not recognized.
Keyword arguments {'source_lang': 'hi'} not recognized.
Keyword arguments {'source_lang': 'hi'} not reco

In [9]:
data.head()

text label
0    We've got a better view of the Britneys tablet.   neg
1                The battery is now fully recharged.   pos
2  The fact is, in the name of metal, only four a...   neu
3  Slofo is a entertainment application that has ...   pos
4                             Good battery capacity.   pos

In [11]:
#WordCloud for the Sentiments
from wordcloud import WordCloud
for label, cmap in zip(['neg', 'pos', 'neu'],
                       ['winter', 'autumn', 'magma', 'viridis', 'plasma']):
    text = ' '.join(data.query('label == @label')['text'])
    plt.figure(figsize=(10, 6))
    wc = WordCloud(width=1000, height=600, background_color="#f8f8f8", colormap=cmap)
    wc.generate_from_text(text)
    plt.imshow(wc)
    plt.axis("off")
    plt.title(f"Words Commonly Used in {label} Messages (Translated)", size=20)
    plt.show()

ValueError: Only supported for TrueType fonts

<Figure size 720x432 with 0 Axes>

In [40]:
# Regular Expression
import re 

# Handling string
import string

# NLP tool
import spacy

nlp=spacy.load('en_core_web_sm')
from spacy.lang.en.stop_words import STOP_WORDS

# Importing Natural Language Tool Kit for NLP operations
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('omw-1.4')                                
from nltk.stem import WordNetLemmatizer

from wordcloud import WordCloud, STOPWORDS
from nltk.corpus import stopwords
from collections import Counter

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Mihika\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Mihika\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Mihika\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Mihika\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [41]:
#defining function for preprocessing
def preprocess(text,remove_digits=True):
    text = re.sub('\W+',' ', text)                                       
    text = re.sub('\s+',' ', text)                                       
    text = re.sub("(?<!\w)\d+", "", text)                                
    text = re.sub("-(?!\w)|(?<!\w)-", "", text)                          
    text=text.lower()
    nopunc=[char for char in text if char not in string.punctuation]    
    nopunc=''.join(nopunc)
    nopunc=' '.join([word for word in nopunc.split()
               if word.lower() not in stopwords.words('english')])  
    
    
    return nopunc
# Defining a function for lemitization
def lemmatize(words):
   
    words=nlp(words)
    lemmas = []
    for word in words:
        
        lemmas.append(word.lemma_)
    return lemmas



#converting them into string
def listtostring(s):
    str1=' '
    return (str1.join(s))

def clean_text(input):
    word=preprocess(input)
    lemmas=lemmatize(word)
    return listtostring(lemmas)

In [42]:
# Creating a feature to store clean texts
data['clean_text']=data['text'].apply(clean_text)
data.head()

text label  \
0    We've got a better view of the Britneys tablet.   neg   
1                The battery is now fully recharged.   pos   
2  The fact is, in the name of metal, only four a...   neu   
3  Slofo is a entertainment application that has ...   pos   
4                             Good battery capacity.   pos   

                                          clean_text  
0                       get well view britney tablet  
1                             battery fully recharge  
2         fact name metal four half line place phone  
3  slofo entertainment application two opinion st...  
4                              good battery capacity

In [43]:
# Vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

# Model Building
from sklearn.model_selection import GridSearchCV,StratifiedKFold,KFold,train_test_split,cross_val_score,cross_val_predict
from sklearn.linear_model import LogisticRegression,SGDClassifier
from sklearn import preprocessing
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import StackingClassifier,RandomForestClassifier,AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier

#Model Evaluation
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,f1_score,precision_score
from sklearn.pipeline import Pipeline

# Time
from time import time

In [44]:
# Defining target & feature for ML model building
x=data['clean_text']
y=data['label']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=1)

In [45]:
# Self-defining function to convert the data into vector form by tf idf 
#vectorizer and classify and create model by Logistic regression

def model_lr_tf(x_train, x_test, y_train, y_test):
    global acc_lr_tf,f1_lr_tf
    # Text to vector transformation 
    vector = TfidfVectorizer()
    x_train = vector.fit_transform(x_train)
    x_test = vector.transform(x_test)
 
    ovr = LogisticRegression()
    
    #fitting training data into the model & predicting
    t0 = time()

    ovr.fit(x_train, y_train)
    
    y_pred = ovr.predict(x_test)
    
    # Model Evaluation
    
    conf=confusion_matrix(y_test,y_pred)
    acc_lr_tf=accuracy_score(y_test,y_pred)
    f1_lr_tf=f1_score(y_test,y_pred,average='weighted')
    print('Time :',time()-t0)
    print('Accuracy: ',acc_lr_tf)
    print(10*'===========')
    print('Confusion Matrix: \n',conf)
    print(10*'===========')
    print('Classification Report: \n',classification_report(y_test,y_pred))
    
    
    return y_test,y_pred,acc_lr_tf

In [46]:
# Self defining function to convert the data into vector form by tf idf 
#vectorizer and classify and create model by MultinomialNB

def model_nb_tf(x_train, x_test, y_train, y_test):
    global acc_nb_tf,f1_nb_tf
    # Text to vector transformation 
    vector = TfidfVectorizer()
    x_train = vector.fit_transform(x_train)
    x_test = vector.transform(x_test)

    ovr = MultinomialNB()
    
    #fitting training data into the model & predicting
    t0 = time()
    
    ovr.fit(x_train, y_train)
    
    y_pred = ovr.predict(x_test)
    
    # Model Evaluation
    
    conf=confusion_matrix(y_test,y_pred)
    acc_nb_tf=accuracy_score(y_test,y_pred)
    f1_nb_tf=f1_score(y_test,y_pred,average='weighted')
    print('Time : ',time()-t0)
    print('Accuracy: ',acc_nb_tf)
    print(10*'===========')
    print('Confusion Matrix: \n',conf)
    print(10*'===========')
    print('Classification Report: \n',classification_report(y_test,y_pred))
    
    
    return y_test,y_pred,acc_nb_tf


In [47]:
# Self defining function to convert the data into vector form by tf idf
# vectorizer and classify and create model by Decision Tree
def model_dt_tf(x_train, x_test, y_train, y_test):
    global acc_dt_tf,f1_dt_tf
    # Text to vector transformation 
    vector = TfidfVectorizer()
    x_train = vector.fit_transform(x_train)
    x_test = vector.transform(x_test)
    

    ovr = DecisionTreeClassifier(random_state=1)
    
    #fitting training data into the model & predicting
    t0 = time()
    
    ovr.fit(x_train, y_train)
    
    y_pred = ovr.predict(x_test)
    
    # Model Evaluation
    
    conf=confusion_matrix(y_test,y_pred)
    acc_dt_tf=accuracy_score(y_test,y_pred)
    f1_dt_tf=f1_score(y_test,y_pred,average='weighted')
    print('Time : ',time()-t0)
    print('Accuracy: ',acc_dt_tf)
    print(10*'===========')
    print('Confusion Matrix: \n',conf)
    print(10*'===========')
    print('Classification Report: \n',classification_report(y_test,y_pred))
    
    
    return y_test,y_pred,acc_dt_tf

In [48]:
# Self defining function to convert the data into vector form by tf idf 
#vectorizer and classify and create model by KNN

def model_knn_tf(x_train, x_test, y_train, y_test):
    global acc_knn_tf,f1_knn_tf
    # Text to vector transformation 
    vector = TfidfVectorizer()
    x_train = vector.fit_transform(x_train)
    x_test = vector.transform(x_test)
    

    ovr = KNeighborsClassifier()
    
    #fitting training data into the model & predicting
    t0 = time()
    
    ovr.fit(x_train, y_train)
    
    y_pred = ovr.predict(x_test)
    
    # Model Evaluation
    
    conf=confusion_matrix(y_test,y_pred)
    acc_knn_tf=accuracy_score(y_test,y_pred)
    f1_knn_tf=f1_score(y_test,y_pred,average='weighted')
    print('Time : ',time()-t0)
    print('Accuracy: ',acc_knn_tf)
    print(10*'===========')
    print('Confusion Matrix: \n',conf)
    print(10*'===========')
    print('Classification Report: \n',classification_report(y_test,y_pred))


In [49]:
# Self defining function to convert the data into vector form by tf idf 
#vectorizer and classify and create model by Random Forest

def model_rf_tf(x_train, x_test, y_train, y_test):
    global acc_rf_tf,f1_rf_tf
    # Text to vector transformation 
    vector = TfidfVectorizer()
    x_train = vector.fit_transform(x_train)
    x_test = vector.transform(x_test)

    ovr = RandomForestClassifier(random_state=1)
    
    #fitting training data into the model & predicting
    t0 = time()
    
    ovr.fit(x_train, y_train)
    
    y_pred = ovr.predict(x_test)
    
    # Model Evaluation
    
    conf=confusion_matrix(y_test,y_pred)
    acc_rf_tf=accuracy_score(y_test,y_pred)
    f1_rf_tf=f1_score(y_test,y_pred,average='weighted')
    print('Time : ',time()-t0)
    print('Accuracy: ',acc_rf_tf)
    print(10*'===========')
    print('Confusion Matrix: \n',conf)
    print(10*'===========')
    print('Classification Report: \n',classification_report(y_test,y_pred))


In [50]:
# Self defining function to convert the data into vector form by tf idf
# vectorizer and classify and create model by Adaptive Boosting

def model_ab_tf(x_train, x_test, y_train, y_test):
    global acc_ab_tf,f1_ab_tf
    # Text to vector transformation 
    vector = TfidfVectorizer()
    x_train = vector.fit_transform(x_train)
    x_test = vector.transform(x_test)
    

    
    ovr = AdaBoostClassifier(random_state=1)
    
    #fitting training data into the model & predicting
    t0 = time()
    
    ovr.fit(x_train, y_train)
    
    y_pred = ovr.predict(x_test)
    
    # Model Evaluation
    
    conf=confusion_matrix(y_test,y_pred)
    acc_ab_tf=accuracy_score(y_test,y_pred)
    f1_ab_tf=f1_score(y_test,y_pred,average='weighted')
    print('Time : ',time()-t0)
    print('Accuracy: ',acc_ab_tf)
    print(10*'===========')
    print('Confusion Matrix: \n',conf)
    print(10*'===========')
    print('Classification Report: \n',classification_report(y_test,y_pred))

In [51]:
# Evaluating Models

print('********************Logistic Regression*********************')
print('\n')
model_lr_tf(x_train, x_test, y_train, y_test)
print('\n')
print(30*'==========')
print('\n')
print('********************Multinomial NB*********************')
print('\n')
model_nb_tf(x_train, x_test, y_train, y_test)
print('\n')
print(30*'==========')
print('\n')
print('********************Decision Tree*********************')
print('\n')
model_dt_tf(x_train, x_test, y_train, y_test)
print('\n')
print(30*'==========')
print('\n')
print('********************KNN*********************')
print('\n')
model_knn_tf(x_train, x_test, y_train, y_test)
print('\n')
print(30*'==========')
print('\n')
print('********************Random Forest Bagging*********************')
print('\n')
model_rf_tf(x_train, x_test, y_train, y_test)
print('\n')
print(30*'==========')
print('\n')
print('********************Adaptive Boosting*********************')
print('\n')
model_ab_tf(x_train, x_test, y_train, y_test)
print('\n')
print(30*'==========')
print('\n')

********************Logistic Regression*********************


Time : 0.7711935043334961
Accuracy:  0.616
Confusion Matrix: 
 [[ 6 13 26]
 [ 0 62 27]
 [ 2 28 86]]
Classification Report: 
               precision    recall  f1-score   support

         neg       0.75      0.13      0.23        45
         neu       0.60      0.70      0.65        89
         pos       0.62      0.74      0.67       116

    accuracy                           0.62       250
   macro avg       0.66      0.52      0.52       250
weighted avg       0.64      0.62      0.58       250





********************Multinomial NB*********************


Time :  0.04286766052246094
Accuracy:  0.608
Confusion Matrix: 
 [[ 1 10 34]
 [ 0 57 32]
 [ 0 22 94]]
Classification Report: 
               precision    recall  f1-score   support

         neg       1.00      0.02      0.04        45
         neu       0.64      0.64      0.64        89
         pos       0.59      0.81      0.68       116

    accuracy            

In [54]:
# Creating tabular format for better comparison
tbl=pd.DataFrame()
tbl['Model']=pd.Series(['Logistic Regresion','Multinomial NB',
            'Decision Tree','Random Forest','Adaptive Boosting'])
tbl['Accuracy']=pd.Series([acc_lr_tf,acc_nb_tf,acc_dt_tf,
                  acc_rf_tf,acc_ab_tf])
tbl['F1_Score']=pd.Series([f1_lr_tf,f1_nb_tf,f1_dt_tf,
                  f1_rf_tf,f1_ab_tf])
tbl.set_index('Model')
# Best model on the basis of F1 Score
tbl.sort_values('F1_Score',ascending=False)

Model  Accuracy  F1_Score
3       Random Forest     0.672  0.648250
0  Logistic Regresion     0.616  0.583644
2       Decision Tree     0.560  0.554250
1      Multinomial NB     0.608  0.551884
4   Adaptive Boosting     0.536  0.522216

In [53]:
# Using cross validation method to avoid overfitting
import statistics as st
vector = TfidfVectorizer()

x_train_v = vector.fit_transform(x_train)
x_test_v  = vector.transform(x_test)

# Model building
lr =LogisticRegression()
mnb=MultinomialNB()
dct=DecisionTreeClassifier(random_state=1)
knn=KNeighborsClassifier()
rf=RandomForestClassifier(random_state=1)
ab=AdaBoostClassifier(random_state=1)
m  =[lr,mnb,dct,knn,rf,ab]
model_name=['Logistic R','MultiNB','DecTRee','KNN','R forest','Ada Boost']

results, mean_results, p, f1_test=list(),list(),list(),list()


#Model fitting,cross-validating and evaluating performance

def algor(model):
    print('\n',i)
    pipe=Pipeline([('model',model)])
    pipe.fit(x_train_v,y_train)
    cv=StratifiedKFold(n_splits=5)
    n_scores=cross_val_score(pipe,x_train_v,y_train,scoring='f1_weighted',
                  cv=cv,n_jobs=-1,error_score='raise') 
    results.append(n_scores)
    mean_results.append(st.mean(n_scores))
    print('f1-Score(train): mean= (%.3f), min=(%.3f)) ,max= (%.3f),stdev= (%.3f)'%(st.mean(n_scores), min(n_scores),max(n_scores),np.std(n_scores)))
    y_pred=cross_val_predict(model,x_train_v,y_train,cv=cv)
    p.append(y_pred)
    f1=f1_score(y_train,y_pred, average = 'weighted')
    f1_test.append(f1)
    print('f1-Score(test): %.4f'%(f1))

for i in m:
    algor(i)


# Model comparison By Visualizing 




 LogisticRegression()
f1-Score(train): mean= (0.626), min=(0.618)) ,max= (0.637),stdev= (0.006)
f1-Score(test): 0.6265

 MultinomialNB()
f1-Score(train): mean= (0.597), min=(0.582)) ,max= (0.619),stdev= (0.015)
f1-Score(test): 0.5972

 DecisionTreeClassifier(random_state=1)
f1-Score(train): mean= (0.601), min=(0.586)) ,max= (0.622),stdev= (0.012)
f1-Score(test): 0.6012

 KNeighborsClassifier()
f1-Score(train): mean= (0.371), min=(0.267)) ,max= (0.563),stdev= (0.125)
f1-Score(test): 0.3919

 RandomForestClassifier(random_state=1)
f1-Score(train): mean= (0.629), min=(0.603)) ,max= (0.649),stdev= (0.021)
f1-Score(test): 0.6295

 AdaBoostClassifier(random_state=1)
f1-Score(train): mean= (0.565), min=(0.544)) ,max= (0.581),stdev= (0.015)
f1-Score(test): 0.5651


In [28]:
x=data['clean_text']
y=data['label']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=1)

vector = TfidfVectorizer()
x_train = vector.fit_transform(x_train)
x_test = vector.transform(x_test)
model_lr_tf=LogisticRegression()

model_lr_tf.fit(x_train,y_train)
y_pred=model_lr_tf.predict(x_test)
# Model Evaluation
    
conf=confusion_matrix(y_test,y_pred)
acc_lr=accuracy_score(y_test,y_pred)
f1_lr=f1_score(y_test,y_pred,average='weighted')

print('Accuracy: ',acc_lr)
print('F1 Score: ',f1_lr)
print(10*'===========')
print('Confusion Matrix: \n',conf)
print(10*'===========')
print('Classification Report: \n',classification_report(y_test,y_pred))

Accuracy:  0.616
F1 Score:  0.5836439326674067
Confusion Matrix: 
 [[ 6 13 26]
 [ 0 62 27]
 [ 2 28 86]]
Classification Report: 
               precision    recall  f1-score   support

         neg       0.75      0.13      0.23        45
         neu       0.60      0.70      0.65        89
         pos       0.62      0.74      0.67       116

    accuracy                           0.62       250
   macro avg       0.66      0.52      0.52       250
weighted avg       0.64      0.62      0.58       250

